apiVersion: v1
kind: Service
metadata:
  name: helm-demo-ms1-service
  namespace: helm-test
spec:
  type: ClusterIP
  selector:
    app: helm-demo-ms1
    component: arc-component
  ports:
   - port: 80
     targetPort: 7777