apiVersion: v1
kind: Service
metadata:
  name: helm-demo-ms1-service
  namespace: helm-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7777
    protocol: TCP
  selector:
    app: helm-demo-ms1
    component: arc-component
  ports:
   - port: 7777
     targetPort: 7777