apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-demo-ms1-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: arc-component
      app: helm-demo-ms1
  template:
    metadata:
      labels:
        app: helm-demo-ms1
        component: arc-component
    spec:
      containers:
        - name: helm-demo-ms1-container
          image: shahankitturn/demo-ms1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7777
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "256Mi"
              cpu: "256m"