#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: helm-demo-ms1
#  annotations:
#    kubernetes.io/ingress.class : nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /
#  namespace: helm-test
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /
#            backend:
#              service:
#                name: helm-demo-ms1-service
#                port:
#                  number: 80