apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arc-demo-ms1
      component: arc-component
  template:
    metadata:
      labels:
        app: arc-demo-ms1
        component: arc-component
    spec:
      containers:
      - name: demo-ms1-pod
        image: us.icr.io/ct-ticketing/demo-ms1:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7777
      imagePullSecrets:
      - name: default-us-icr-io