apiVersion: v1
kind: Secret
data: 
    .dockerconfigjson: eyJhdXRocyI6eyJ1cy5pY3IuaW8iOnsidXNlcm5hbWUiOiJpYW1hcGlrZXkiLCJwYXNzd29yZCI6IlRuaU95MG9CVklHUnVRS3hPeklZdkpMR3hDTlhzVDdIb2FGYURNdVVxM25kIiwiZW1haWwiOiJpYW1hcGlrZXkiLCJhdXRoIjoiYVdGdFlYQnBhMlY1T2xSdWFVOTVNRzlDVmtsSFVuVlJTM2hQZWtsWmRrcE1SM2hEVGxoelZEZEliMkZHWVVSTmRWVnhNMjVrIn19fQ==
metadata:
    name: default-us-icr-io
    namespace: helm-test
type: kubernetes.io/dockerconfigjson